### ISSUE TITLE
About some questions

### ISSUE THREAD

**Issue by Lucia-Rubio-E** [t-34400/MetaQuestScreenBarcodeReader#1]
Could I contact you through this email: lucia.rubio@uah.es to ask you any more questions about the implementation of this project?

**Comment by t-34400** [comment]
Hi Lucia-Rubio-E,
You're welcome to contact me at the email address 34400mt_at_gmail.com with any questions you may have. 
Alternatively, if you're comfortable with it being public, please don't hesitate to open an issue on this GitHub repository and ask your questions there.

**Comment by t-34400** [comment]
Hi Lucia-Rubio-E,
I've created a standalone version of the server, so I'm going to archive this repository. Here's the link to the new repository: [link](https://github.com/t-34400/MetaQuestScreenCaptureServer/tree/master?tab=readme-ov-file). 
Take a look whenever you have a moment.
